---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - wget

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../:extra_roles' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/travisci/tests.yml -i tests/travisci/inventory --syntax-check

  # download the QA scripts
  - mkdir bin
  - wget -O bin/ansible-role-qa https://gist.githubusercontent.com/trombik/047364853d2f8070da9d4f360b4b9da9/raw
  - wget -O bin/ansible-role-init https://gist.githubusercontent.com/trombik/d01e280f02c78618429e334d8e4995c0/raw
  - chmod +x bin/*

  # use recent ruby, instead of default ruby 1.9
  - rvm install ruby-2.1.10
  - rvm use 2.1.10

  # git complains if user and email are not set
  - git config --global user.name "Your Name"
  - git config --global user.email "you@example.com"

  # surpress a warning from `ansible-role-qa`
  - touch .kitchen.local.yml

  # run the QA test
  - export PATH="${PATH}:${PWD}/bin"
  - ansible-role-qa

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
